ALTER TABLE search_histories
    ADD COLUMN IF NOT EXISTS user_contacted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS contacted_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS user_note TEXT;
